#ifndef _KIPR_CONFIG_H_
#define _KIPR_CONFIG_H_

#define KIPR_GIT_BRANCH "refactor"
#define KIPR_GIT_COMMIT_HASH "28277735baa490a0ef88f7aac51b1b1091d1bfb2"
#define KIPR_VERSION_MAJOR 1
#define KIPR_VERSION_MINOR 0
#define KIPR_VERSION_PATCH 0
#define KIPR_VERSION "1.0.0"
#define KIPR_BUILD_DATETIME "2023-02-04T22:38:18Z"

#define KIPR_MODULE_ACCEL
#define KIPR_MODULE_ANALOG
#define KIPR_MODULE_AUDIO
#define KIPR_MODULE_BATTERY
#define KIPR_MODULE_BOTBALL
#define KIPR_MODULE_BUTTON
#define KIPR_MODULE_CAMERA
#define KIPR_MODULE_COLOR
#define KIPR_MODULE_COMPASS
#define KIPR_MODULE_COMPAT
#define KIPR_MODULE_CONFIG
#define KIPR_MODULE_CONSOLE
#define KIPR_MODULE_CORE
#define KIPR_MODULE_CREATE
#define KIPR_MODULE_DIGITAL
#define KIPR_MODULE_GEOMETRY
#define KIPR_MODULE_GRAPHICS
#define KIPR_MODULE_GYRO
#define KIPR_MODULE_MAGNETO
#define KIPR_MODULE_MOTOR
#define KIPR_MODULE_NETWORK
#define KIPR_MODULE_SENSOR
#define KIPR_MODULE_SERVO
#define KIPR_MODULE_TELLO
#define KIPR_MODULE_THREAD
#define KIPR_MODULE_TIME
#define KIPR_MODULE_WAIT_FOR

#endif
